name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'
          architecture: 'x64'
          token: ${{ github.token }}
      - name: Build with Python
        run: |
          pip install chess
          python ./build.py

      - name: Copy Binary
        run: python ./copy.py

      - name: Self play
        run: python ./build.py --test

      - name: Bench
        run: ./rustfish bench